# Generated by Django 5.0.6 on 2024-06-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Slaugherhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTransportCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of_year', models.IntegerField()),
                ('max_transport_capacity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAnimalTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_cost', models.FloatField(default=0)),
                ('week_of_year', models.IntegerField()),
                ('destination_slaughterhouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opti.slaugherhouse')),
                ('origin_farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opti.farm')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyFarmAnimalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_count', models.IntegerField(default=0)),
                ('average_weight', models.FloatField(default=0)),
                ('week_of_year', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opti.farm')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySlaughterhouseDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_count', models.IntegerField(default=0)),
                ('live_animal_price_per_kg', models.FloatField(default=0)),
                ('week_of_year', models.IntegerField()),
                ('slaughterhouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opti.slaugherhouse')),
            ],
        ),
    ]
